### PR TITLE
Adding category images

### LINKED ISSUE #39: Category Images
Lets get some fancy looking images to improve the look of the homepage now we dont have all the links on there.

### PR DESCRIPTION
**Pull request by philsturgeon**
Closes #39, or at least it will when I fix the "infamous" field image string error:

> Field "image" must not have a selection since type "String" has no subfields

Tried every bit of advice including:

- https://theleakycauldronblog.com/blog/problems-with-gatsby-image-and-their-workarounds/
- https://github.com/gatsbyjs/gatsby/issues/4123
- https://github.com/gatsbyjs/gatsby/issues/13469

Help...

### CODE REVIEW

**Comment by philsturgeon** [comment]
@stephensamra do you have any ideas on this one? I lost a lot of time to it.

**Comment by stephensamra** [comment]
@philsturgeon I'll try to take a look today if I get the time. If not, it might be Wednesday before I get a chance to look at it.

**Comment by stephensamra** [comment]
@philsturgeon Figured it out - the path to the image in the category files should be `../images/cat.jpg`.

With that change, we have cats 🐱!
image

**Comment by philsturgeon** [comment]
Thank you so much! I wish they had a better error which made this more clear. 🤦🏻‍♂️

**Pull request merged**
