### PR TITLE
Another another netlify CMS attempt

### PR DESCRIPTION
**Pull request by mbifulco**
I can't figure out how to get this damn thing to work in a local env

### CODE REVIEW

**Comment by mbifulco** [comment]
This PR also contains the following:
- a `.nvmrc` file, which will tell netlify to build this with the most recent version of node.  
- a bunch of updates to gatsby dependencies, because something wasn't working locally when I tried to build
- a sytax fix
- removal of a `debugger;` line that was gumming up my debug attempts

**Comment by HeidiHansen** [comment]
Did you get it to work? I'm able to run locally using with npm and Chrome.  I do still get the following error with Firefox:  

image

**Comment by mbifulco** [comment]
Hey @HeidiHansen - it's tough to tell how this is going.  I can get to the admin interface locally, but authentication doesn't seem to work.  Same thing with deploy previews - so far it only seems to be happy in production.  If I can't get this to work in the next couple tries, I'm going to see if I can find some help on the NetlifyCMS slack team

**Comment by mbifulco** [comment]
We're getting closer.  I think I may need to reformat `links.yaml` - it's still not seeing any links in there

It knows about the file list:
image

But shows it as empty:
image

**Pull request merged**
