### PR TITLE
Add jobs category, image and relevant links

### LINKED ISSUE #137: Jobs category
https://climate.careers/
https://greenjobs.glideapp.io/
https://jobs.theguardian.com/jobs/climate-change/
https://www.goodwork.ca/
https://greenjobs.com/

### PR DESCRIPTION
**Pull request by giovannidisiena**
Closes #137

### CODE REVIEW

**Comment by giovannidisiena** [comment]
@philsturgeon I don't have access to the CI - would you be able to let me know why the checks are failing please?

**Comment by HeidiHansen** [comment]
@giovannidisiena, this could have been failing due to the use of 'uk' instead of 'gb' for country code.

**Comment by giovannidisiena** [comment]
@HeidiHansen good spot, thank you!

**Comment by philsturgeon** [comment]
dont worry i sorted it out. I've made the same mistake many times. Also you had a .jpg vs .jpeg which I've also done many times.

**Comment by giovannidisiena** [comment]
@philsturgeon ahh, well thank you both!

**Comment by philsturgeon** [comment]
If you have it in you to do another, the #130 could do with similar treatment. If you do it, please look for existing food stuff in our links and move em over too.

**Comment by giovannidisiena** [comment]
@philsturgeon if I have some time free up then I will do!

**Pull request merged**
