### PR TITLE
WIP Redesign

### PR DESCRIPTION
**Pull request by mbifulco**
Take 2... a _draft_ PR to work on redesign per #50

### CODE REVIEW

**Comment by mbifulco** [comment]
@philsturgeon the home page here is ready for a cursory look.  I did my best to clean up what was there prior and align it to the mockups in #50.  There's still work to be done on the category page.  I'll try to get to that in the morning.

# To do
- [ ] category page
- [ ] content for `About` 
- [ ] content for `Contribute`
- [ ] wire up Search
- [ ] footer content? What should go there.  We could 
- [ ] country select page could use some redesign work, too


# Screenshot
image

**Comment by mbifulco** [comment]
Added updates for category page - if there's >6 links, I add a featured section/jumbotron at the top:

image

**Comment by mbifulco** [comment]
Alright y'all - I created the `about` page.  It could use some content.  Anyone wanna write that up?

**Comment by philsturgeon** [comment]
This is going great! i commented out search, removed the fork, and pushed it back. 

@stephensamra you're off the hook with the redesign! 

Seems like country filter has died in this branch though, could somebody figure that out?

**Comment by philsturgeon** [comment]
Fixed markdown rendering for feature descriptions, got features pickable via `featured: true` in inks.yaml, deleted the old carousel and put the cards in a card deck. 

Search and Country Filter are hidden for now so don't worry about them, they can be worked on in #18 and #83.

We need to bring back the #64 which have gone missing in this version, and the category images get a bit stretched on certain widths.

**Comment by mbifulco** [comment]
Heck yeah! Thanks for getting this to the finish line for now Phil.  Looking forward to spending more time with this.

**Pull request merged**
