### PR TITLE
Feature/recent links

### LINKED ISSUE #118: Recent Links
I've been throwing new links in at the bottom, which means we can do a "recent links" just by popping a few off the end. Let's get this up on the homepage somehow.

### PR DESCRIPTION
**Pull request by ijpatricio**
Hey @philsturgeon ! is this what you were expecting? 

Did I miss something? I can't find the route for categories and tags pages..

Fixes #118 

image

### CODE REVIEW

**Comment by philsturgeon** [comment]
This looks great! Watch out for conflicts.

The categories page is protect.earth/travel and the tags page is /tags/developers.

Of course we don’t need to list tags on the tags page but we should make our lists look a bit more consistent in style in general.

**Comment by lucasfonmiranda** [comment]
@ijpatricio can you do that: https://github.com/philsturgeon/awesome-earth/pull/140#issuecomment-580929276

**Comment by ijpatricio** [comment]
Don't know how, I missed your comment @lucasfonmiranda sorry!
The looks on the picture (https://github.com/philsturgeon/awesome-earth/pull/140#issue-369770744) is already done.

@philsturgeon thanks! what conflicts??
hmm what should happen if someone visits `/ tags` ?

Would love to compile the needs for next step:
- List articles that have the selected tag
- Implement component for (agnostic) lists, that will render
  - RecentLinks
  - Categories
  - What more?

**Comment by philsturgeon** [comment]
> @philsturgeon thanks! what conflicts??

image

> hmm what should happen if someone visits / tags ?

No need to make that here.

> Would love to compile the needs for next 

1. Fix PR conflicts
2. Make sure recent links are most recent at the top
3. Implement component for (agnostic) lists, that will render
  - Recent Links
  - Category Links
  - Tag Links

Sound good? :D

**Comment by ijpatricio** [comment]
@philsturgeon 

### done
- so I missed the conflicts before, all good now
- sorting fixed
- tag text font smaller and lighter
- tag badge now goes to `/tags/{tag}`


### doubts
About the listing uniformity:
- category page
image

- tag page
image

- homepage (recentlinks)
image

these are the three lists that are not coherent, right?

do you have an idea of how it should be, or free will?

**Comment by philsturgeon** [comment]
Combining them all somehow to make them ccoherent is the goal yeah. We don't need the paragraphs to be links, we want share buttons on all of them (even if the icons need to be a bit smaller) and everything thats not the Tags page should show tags. Then they'll all match :D

**Comment by philsturgeon** [comment]
I've gone ahead and merged this, it's looking much better than what's there. @ijpatricio could you do another PR to make lists look more similar?

**Comment by ijpatricio** [comment]
Thanks @philsturgeon 
Yep, let’s do it!

**Pull request merged**
