### PR TITLE
Try netlify CMS for adding links

### LINKED ISSUE #69: Submissions Form
Let people suggest their own links via a Netlify form. 

https://www.netlify.com/products/forms/

### PR DESCRIPTION
**Pull request by mbifulco**
**Note:** I haven't been able to test this at all, because I need access to netlify to configure the CMS.  Opening this PR so @philsturgeon can give it a shot.

# What this PR does
This sets up [netlify CMS](https://www.netlifycms.org/) as a means to accept new content on the site.  I believe I've enabled [open authoring](https://www.netlifycms.org/docs/beta-features/#open-authoring) submissions, which will allow people to submit to the CMS publishing workflow without having access to (or knowledge of) this repo.

This will fix #69 if it works!

To test:
1. run this branch locally (or possibly on deploy preview)
1. go to `/admin` and follow steps from there

### CODE REVIEW

**Comment by philsturgeon** [comment]
Enabled Identity on the site and enabled GitHub as normal Netlify Identity. Its sending me in circles trying to sign in. This is all new and confusing and I feel like an old man shouting at the television. Can we do a quick pair to fix it?

**Comment by philsturgeon** [comment]
OH it emailed me a confirmation email and now I get this:

> Your Git Gateway backend is not returning valid settings. Please make sure it is enabled.

**Comment by mbifulco** [comment]
I can work on it now if you're around - I'll ping you.

**Comment by mbifulco** [comment]
Git gateway instructions are [here](https://docs.netlify.com/visitor-access/git-gateway/#setup-and-settings)

**Pull request merged**
