### PR TITLE
Changed Palm-Oil Free Products entry

### PR DESCRIPTION
**Pull request by hematogender**
Palm-Oil Free Products link is just an article explaining the harm of products containing palm-oil.
Also, this entry looks broken because of the Palm-Oil Free Beauty Brands link later in the description.
I changed Palm-Oil Free Products links in favor of Palm-Oil Free Beauty Brands, which both explains the problem and actually contains a list of brands selling palm-oil free products.

### CODE REVIEW

**Comment by philsturgeon** [comment]
The weird line breaks on the link is fine, redesign (#50) is coming. Linking to an article is not a bug, and it was meant to be about more than just beauty brands. Can we use both links somehow?

**Comment by hematogender** [comment]
@philsturgeon Oh, didn't know about the redesign thing (cool!). But really, the first link doesn't tell about any products at all. The second one is only about beauty brands, too.

So I figured why don't we make [this big list](https://www.ethicalconsumer.org/palm-oil/palm-oil-free-list) the main one and add [this explanatory article](https://www.sustainablejungle.com/sustainable-living/palm-oil-free/) in the description? Every other entry focuses on brands, not just info, so it would be a great way to both explain a problem and to provide a solution.

Let me know what you think!

**Comment by philsturgeon** [comment]
I prefer general advisory over specific products when applicable. Some other links are pointing to Wikipedia explaining general concepts, but we can put specific links in the description too to help people. This page is very UK-specific for example, so non-Brits are not going to get as much out of the page. 

The UK page could be another link, or go in the description?

**Comment by HeidiHansen** [comment]
I dug into these links and found The Orangutan Foundation International's [info page](https://orangutanfoundation.org.au/palm-oil/) about palm oil.  I think we should use this one, but I do think we should also link to the UK site because it's really well done and has tons of info.

**Comment by philsturgeon** [comment]
@HeidiHansen can you make a super PR with all the things you suggested? :)

**Pull request merged**
